version: '3.8'

# START COMMAND
# docker-compose -f docker-compose.weavescope.yml up -d

services:
  
  scope:
    container_name: weavescope
    image: weaveworks/scope:master-5373b5ea # current latest, working!
    privileged: true
    pid: host
    ports:
      - '4040:4040'
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw" # linux
      - "/usr/local/bin/docker:/usr/bin/docker:rw"  # windows
    command:
      - "--probe.docker=true"
      #- "--weave=false"
